# Generated by Django 3.1.1 on 2020-10-18 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rms', '0004_auto_20201017_2341'),
    ]

    operations = [
        migrations.CreateModel(
            name='siteDtls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sid', models.CharField(blank=True, max_length=30, null=True)),
                ('ConNum', models.IntegerField(blank=True, null=True)),
                ('ConName', models.CharField(blank=True, max_length=30, null=True)),
                ('ConMob', models.IntegerField(blank=True, max_length=10, null=True)),
                ('LocName', models.CharField(blank=True, max_length=30, null=True)),
                ('PumpDtls', models.CharField(blank=True, max_length=30, null=True)),
                ('InvDtls', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
    ]
