# Generated by Django 3.1.1 on 2020-10-20 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rms', '0005_sitedtls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='md',
            name='Date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
