# Generated by Django 3.1.1 on 2021-03-14 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rms', '0008_auto_20201020_1746'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mdtls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rmsId', models.CharField(blank=True, max_length=30, null=True)),
                ('Date', models.DateField(blank=True, null=True)),
                ('dcenergy', models.FloatField(blank=True, null=True)),
                ('prthrs', models.FloatField(blank=True, null=True)),
                ('lpd', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='dd',
        ),
        migrations.DeleteModel(
            name='md',
        ),
        migrations.RenameField(
            model_name='sitedtls',
            old_name='InvDtls',
            new_name='capacity',
        ),
        migrations.RenameField(
            model_name='sitedtls',
            old_name='LocName',
            new_name='cmcY',
        ),
        migrations.RenameField(
            model_name='sitedtls',
            old_name='PumpDtls',
            new_name='location',
        ),
        migrations.RemoveField(
            model_name='sitedtls',
            name='ConMob',
        ),
        migrations.RemoveField(
            model_name='sitedtls',
            name='ConName',
        ),
        migrations.RemoveField(
            model_name='sitedtls',
            name='ConNum',
        ),
        migrations.RemoveField(
            model_name='sitedtls',
            name='Sid',
        ),
        migrations.AddField(
            model_name='sitedtls',
            name='custMob',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitedtls',
            name='custName',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='sitedtls',
            name='poNo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sitedtls',
            name='regID',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='sitedtls',
            name='rmsId',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
