# Generated by Django 3.1.1 on 2021-03-14 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rms', '0011_auto_20210314_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitedata',
            name='Date',
            field=models.DateField(blank=True, help_text='Date of Data', null=True),
        ),
        migrations.AlterField(
            model_name='sitedetails',
            name='capacity',
            field=models.CharField(blank=True, choices=[('5HP AC', '5HP AC'), ('3HP AC', '3HP AC'), ('7.5HP AC', '7.5HP AC'), ('10HP AC', '10HP AC'), ('5HP DC', '5HP DC'), ('3HP DC', '3HP DC'), ('7.5HP DC', '7.5HP DC'), ('10HP DC', '10HP DC')], help_text='5HP AC or 3HP AC or other', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='sitedetails',
            name='custMob',
            field=models.IntegerField(blank=True, help_text='Customer Contact Number', null=True),
        ),
        migrations.AlterField(
            model_name='sitedetails',
            name='custName',
            field=models.CharField(blank=True, help_text='Customer Name', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='sitedetails',
            name='regID',
            field=models.CharField(blank=True, help_text='If any registration ID is there then fill', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='sitedetails',
            name='rmsId',
            field=models.CharField(blank=True, help_text='Serial No-1, 2 etc or RMS ID', max_length=40, null=True),
        ),
    ]
