# Generated by Django 3.1.1 on 2021-03-15 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rms', '0012_auto_20210314_1752'),
    ]

    operations = [
        migrations.CreateModel(
            name='homeid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('homeId', models.CharField(blank=True, max_length=40, null=True)),
            ],
        ),
    ]
