# Generated by Django 3.1.1 on 2021-04-01 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rms', '0013_homeid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitedetails',
            old_name='custMob',
            new_name='CustMob',
        ),
        migrations.RemoveField(
            model_name='sitedata',
            name='dcenergy',
        ),
        migrations.RemoveField(
            model_name='sitedata',
            name='lpd',
        ),
        migrations.RemoveField(
            model_name='sitedata',
            name='prthrs',
        ),
        migrations.RemoveField(
            model_name='sitedata',
            name='rmsId',
        ),
        migrations.RemoveField(
            model_name='sitedetails',
            name='capacity',
        ),
        migrations.RemoveField(
            model_name='sitedetails',
            name='cmcY',
        ),
        migrations.RemoveField(
            model_name='sitedetails',
            name='custName',
        ),
        migrations.RemoveField(
            model_name='sitedetails',
            name='location',
        ),
        migrations.RemoveField(
            model_name='sitedetails',
            name='poNo',
        ),
        migrations.RemoveField(
            model_name='sitedetails',
            name='regID',
        ),
        migrations.RemoveField(
            model_name='sitedetails',
            name='rmsId',
        ),
        migrations.AddField(
            model_name='sitedata',
            name='Current',
            field=models.FloatField(blank=True, help_text='Running PV Current in Amps', null=True),
        ),
        migrations.AddField(
            model_name='sitedata',
            name='DateTime',
            field=models.DateTimeField(blank=True, help_text='Date and Time of Data', null=True),
        ),
        migrations.AddField(
            model_name='sitedata',
            name='DayEnergy',
            field=models.FloatField(blank=True, help_text='Day Energy in Kwh', null=True),
        ),
        migrations.AddField(
            model_name='sitedata',
            name='Energy',
            field=models.FloatField(blank=True, help_text='Running Energy in Kwh', null=True),
        ),
        migrations.AddField(
            model_name='sitedata',
            name='Fault',
            field=models.CharField(blank=True, choices=[('Dry Run', 'Dry Run'), ('Motor Jam', 'Motor Jam'), ('Open CKT', 'Open CKT'), ('Short CKT', 'Short CKT'), ('Over Currents', 'Over Currents'), ('Over Heat', 'Over Heat')], help_text='Name of the Fault', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sitedata',
            name='Frequency',
            field=models.FloatField(blank=True, help_text='Running Motor Frequency in Hz', null=True),
        ),
        migrations.AddField(
            model_name='sitedata',
            name='GrossEnergy',
            field=models.FloatField(blank=True, help_text='Total Gross Energy in Kwh', null=True),
        ),
        migrations.AddField(
            model_name='sitedata',
            name='GrossLPD',
            field=models.IntegerField(blank=True, help_text='Total Gross Flow in Liters', null=True),
        ),
        migrations.AddField(
            model_name='sitedata',
            name='LPD',
            field=models.IntegerField(blank=True, help_text='Total Day Flow in Liters', null=True),
        ),
        migrations.AddField(
            model_name='sitedata',
            name='LPH',
            field=models.IntegerField(blank=True, help_text='Flow Rate in LPH', null=True),
        ),
        migrations.AddField(
            model_name='sitedata',
            name='MotorCurrent',
            field=models.FloatField(blank=True, help_text='Running Motor Current in Amps', null=True),
        ),
        migrations.AddField(
            model_name='sitedata',
            name='MotorVoltage',
            field=models.IntegerField(blank=True, help_text='Running Motor Voltage in Volts', null=True),
        ),
        migrations.AddField(
            model_name='sitedata',
            name='Power',
            field=models.FloatField(blank=True, help_text='Power in Kw', null=True),
        ),
        migrations.AddField(
            model_name='sitedata',
            name='PumpRunHours',
            field=models.FloatField(blank=True, help_text='Pump Running Hours', null=True),
        ),
        migrations.AddField(
            model_name='sitedata',
            name='Rid',
            field=models.CharField(blank=True, help_text='Serial No-1, 2 etc or RMS ID', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sitedata',
            name='RunStatus',
            field=models.BooleanField(default=False, help_text='Running Status'),
        ),
        migrations.AddField(
            model_name='sitedata',
            name='TankFull',
            field=models.BooleanField(default=False, help_text='State of Tank'),
        ),
        migrations.AddField(
            model_name='sitedata',
            name='Temp',
            field=models.FloatField(blank=True, help_text='Temperature in Degree Cent', null=True),
        ),
        migrations.AddField(
            model_name='sitedata',
            name='Voltage',
            field=models.IntegerField(blank=True, help_text='Running PV Voltage in Volts', null=True),
        ),
        migrations.AddField(
            model_name='sitedetails',
            name='Block',
            field=models.CharField(blank=True, help_text='Block', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sitedetails',
            name='CSno',
            field=models.CharField(blank=True, help_text='Controller Make, Serial No', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sitedetails',
            name='Capacity',
            field=models.CharField(blank=True, choices=[('1HP DC', '1HP DC'), ('2HP DC', '2HP DC'), ('5HP AC', '5HP AC'), ('3HP AC', '3HP AC'), ('7.5HP AC', '7.5HP AC'), ('10HP AC', '10HP AC'), ('5HP DC', '5HP DC'), ('3HP DC', '3HP DC'), ('7.5HP DC', '7.5HP DC'), ('10HP DC', '10HP DC')], help_text='Pump Capacity in HP', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='sitedetails',
            name='CustName',
            field=models.CharField(blank=True, help_text='Customer Name', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sitedetails',
            name='DateInst',
            field=models.DateField(blank=True, help_text='Installation Date', null=True),
        ),
        migrations.AddField(
            model_name='sitedetails',
            name='District',
            field=models.CharField(blank=True, help_text='District', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sitedetails',
            name='Habitation',
            field=models.CharField(blank=True, help_text='Name of Habitation', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sitedetails',
            name='LatLong',
            field=models.CharField(blank=True, help_text='Latitude, Longitude', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='sitedetails',
            name='Mandal',
            field=models.CharField(blank=True, help_text='Mandal', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sitedetails',
            name='PSno',
            field=models.CharField(blank=True, help_text='Pump Make, Serial No', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sitedetails',
            name='Panchayat',
            field=models.CharField(blank=True, help_text='Gram Panchayat', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sitedetails',
            name='PanelWp',
            field=models.IntegerField(blank=True, help_text='Total Panel Wattage in Watts', null=True),
        ),
        migrations.AddField(
            model_name='sitedetails',
            name='Pid',
            field=models.CharField(blank=True, help_text='Project/PO Ref No', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sitedetails',
            name='PumpHead',
            field=models.IntegerField(blank=True, help_text='Pump Head', null=True),
        ),
        migrations.AddField(
            model_name='sitedetails',
            name='Rid',
            field=models.CharField(blank=True, help_text='Serial No-1, 2 etc or RMS ID', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sitedetails',
            name='SimNo',
            field=models.CharField(blank=True, help_text='SIM Number', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sitedetails',
            name='State',
            field=models.CharField(blank=True, choices=[('Rajasthan', 'Rajasthan'), ('Chhattisgarh', 'Chhattisgarh'), ('Andhra Pradesh', 'Andhra Pradesh')], help_text='Name of the State', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='sitedetails',
            name='Village',
            field=models.CharField(blank=True, help_text='Village', max_length=50, null=True),
        ),
    ]
