# Generated by Django 3.1.1 on 2021-09-16 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rms', '0014_auto_20210401_2141'),
    ]

    operations = [
        migrations.CreateModel(
            name='BHData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CID_No', models.CharField(blank=True, help_text='Serial No-1, 2 etc or RMS ID', max_length=50, null=True)),
                ('Date', models.DateField(blank=True, help_text='Date of Data', null=True)),
                ('DateTime', models.DateTimeField(blank=True, help_text='Date and Time of Data', null=True)),
                ('LPH', models.IntegerField(blank=True, help_text='Flow Rate in LPH', null=True)),
                ('LPD', models.IntegerField(blank=True, help_text='Total Day Flow in Liters', null=True)),
                ('GrossLPD', models.IntegerField(blank=True, help_text='Total Gross Flow in Liters', null=True)),
                ('Power', models.FloatField(blank=True, help_text='Power in Kw', null=True)),
                ('Energy', models.FloatField(blank=True, help_text='Running Energy in Kwh', null=True)),
                ('DayEnergy', models.FloatField(blank=True, help_text='Day Energy in Kwh', null=True)),
                ('GrossEnergy', models.FloatField(blank=True, help_text='Total Gross Energy in Kwh', null=True)),
                ('Voltage', models.IntegerField(blank=True, help_text='Running PV Voltage in Volts', null=True)),
                ('Current', models.FloatField(blank=True, help_text='Running PV Current in Amps', null=True)),
                ('MotorVoltage', models.IntegerField(blank=True, help_text='Running Motor Voltage in Volts', null=True)),
                ('MotorCurrent', models.FloatField(blank=True, help_text='Running Motor Current in Amps', null=True)),
                ('Frequency', models.FloatField(blank=True, help_text='Running Motor Frequency in Hz', null=True)),
                ('Temp', models.FloatField(blank=True, help_text='Temperature in Degree Cent', null=True)),
                ('PumpRunHours', models.FloatField(blank=True, help_text='Pump Running Hours', null=True)),
                ('Fault', models.CharField(blank=True, choices=[('Dry Run', 'Dry Run'), ('Motor Jam', 'Motor Jam'), ('Open CKT', 'Open CKT'), ('Short CKT', 'Short CKT'), ('Over Currents', 'Over Currents'), ('Over Heat', 'Over Heat')], help_text='Name of the Fault', max_length=50, null=True)),
                ('RunStatus', models.BooleanField(default=False, help_text='Running Status')),
            ],
        ),
        migrations.CreateModel(
            name='BHInstData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CID_No', models.CharField(blank=True, help_text='Claro ID', max_length=10, null=True)),
                ('Date', models.DateField(blank=True, help_text='Date of Data', null=True)),
                ('Time', models.TimeField(blank=True, help_text='Date of Data', null=True)),
                ('Voltage', models.IntegerField(blank=True, help_text='Running PV Voltage in Volts', null=True)),
                ('Current', models.FloatField(blank=True, help_text='Running PV Current in Amps', null=True)),
                ('Power', models.FloatField(blank=True, help_text='Power in Kw', null=True)),
                ('Frequency', models.FloatField(blank=True, help_text='Running Motor Frequency in Hz', null=True)),
                ('Energy', models.FloatField(blank=True, help_text='Running Energy in Kwh', null=True)),
                ('GrossEnergy', models.FloatField(blank=True, help_text='Total Gross Energy in Kwh', null=True)),
                ('LPD', models.IntegerField(blank=True, help_text='Total Day Flow in Liters', null=True)),
                ('GrossLPD', models.IntegerField(blank=True, help_text='Total Gross Flow in Liters', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BHSiteDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CID_No', models.CharField(blank=True, help_text='Claro ID', max_length=10, null=True)),
                ('Project_Code', models.CharField(blank=True, help_text='Project Code', max_length=50, null=True)),
                ('VFD_Make', models.CharField(blank=True, help_text='Controller Make', max_length=50, null=True)),
                ('Pump_Make', models.CharField(blank=True, help_text='Pump Make', max_length=100, null=True)),
                ('VFD_No', models.CharField(blank=True, help_text='VFD Serial No', max_length=50, null=True)),
                ('Pump_No', models.CharField(blank=True, help_text='VFD Serial No', max_length=50, null=True)),
                ('Capacity', models.CharField(blank=True, help_text='Pump Capacity in HP', max_length=10, null=True)),
                ('Cust_Name', models.CharField(blank=True, help_text='Customer Name', max_length=50, null=True)),
                ('Fath_Name', models.CharField(blank=True, help_text='Customer Father Name', max_length=50, null=True)),
                ('Cust_Mob', models.CharField(blank=True, max_length=10, null=True)),
                ('Village', models.CharField(blank=True, help_text='Village', max_length=50, null=True)),
                ('Block', models.CharField(blank=True, help_text='Block', max_length=50, null=True)),
                ('District', models.CharField(blank=True, help_text='District', max_length=50, null=True)),
                ('State', models.CharField(blank=True, help_text='State', max_length=50, null=True)),
                ('Date_Inst', models.DateField(blank=True, help_text='Installation Date', null=True)),
            ],
        ),
    ]
