# Generated by Django 3.1.1 on 2021-09-16 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rms', '0016_auto_20210916_1355'),
    ]

    operations = [
        migrations.CreateModel(
            name='DBData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CID_No', models.CharField(blank=True, help_text='Serial No-1, 2 etc or RMS ID', max_length=50, null=True)),
                ('GrossLPD', models.IntegerField(blank=True, help_text='Total Gross Flow in Liters', null=True)),
                ('GrossEnergy', models.FloatField(blank=True, help_text='Total Gross Energy in Kwh', null=True)),
                ('PumpRunHours', models.FloatField(blank=True, help_text='Pump Running Hours', null=True)),
                ('Faults', models.IntegerField(blank=True, help_text='Total Faults', null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='bhsitedetails',
            name='Type',
            field=models.CharField(blank=True, choices=[('Submersible', 'Submersible'), ('Surface', 'Surface')], help_text='Pump Capacity in HP', max_length=20, null=True),
        ),
    ]
