# Generated by Django 3.1.1 on 2021-09-16 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rms', '0017_auto_20210916_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dbdata',
            name='GrossEnergy',
            field=models.IntegerField(blank=True, help_text='Total Gross Energy in Kwh', null=True),
        ),
        migrations.AlterField(
            model_name='dbdata',
            name='PumpRunHours',
            field=models.IntegerField(blank=True, help_text='Pump Running Hours', null=True),
        ),
    ]
