# Generated by Django 3.1.1 on 2021-09-17 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rms', '0018_auto_20210916_1627'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homeid',
            old_name='homeId',
            new_name='CID_No',
        ),
        migrations.AddField(
            model_name='homeid',
            name='Date',
            field=models.DateField(blank=True, help_text='Date of Data', null=True),
        ),
        migrations.AddField(
            model_name='homeid',
            name='Status',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homeid',
            name='dtm',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homeid',
            name='eTime',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homeid',
            name='sTime',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homeid',
            name='step',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
